// TEST ONLY. Stand-in for the Gemini endpoint in the local simulation. Example:
//   NODE_OPTIONS=--import=./test/sim/mock-gemini.mjs node test/sim/worker.mjs setup <workspaceId>
// Intercepts calls to the Gemini endpoint so the real CLI, workflow command and
// gemini.mjs transport run end to end without any network call to Google.
// MOCK_GEMINI=429 simulates a quota error. Everything else passes through.
import fs from 'node:fs';

const realFetch = globalThis.fetch;
const example = JSON.parse(fs.readFileSync(new URL('../../config/examples/betterspace-b2b.setup-package.json', import.meta.url), 'utf8'));
const norm = v => String(v ?? '').replace(/^﻿/, '').trim().toLowerCase();
const log = [];

function mapTable(name, rows) {
  const headerIdx = rows.findIndex(r => r.some(v => /_id$/.test(norm(v))));
  if (headerIdx < 0) return null;
  const headers = rows[headerIdx].map(norm);
  for (const t of example.tables) {
    if (t.fields.every(f => !f.header || headers.includes(norm(f.header)))) {
      const original = rows[headerIdx];
      return { name, entity: t.entity, header_row: headerIdx + 1, fields: t.fields.filter(f => f.header).map(f => ({ canonical: f.canonical, header: String(original[headers.indexOf(norm(f.header))]) })) };
    }
  }
  return null;
}

function mappingAnswer(request) {
  const source = request.source;
  let tables = source.tables || [];
  const document_tables = [];
  if (source.text) {
    const rows = source.text.split('\n').map(l => l.trim()).filter(l => l.includes(' | ')).map(l => l.split(' | ').map(s => s.trim()));
    if (rows.length) { document_tables.push({ name: 'Payments (from PDF)', rows }); tables = document_tables; }
  }
  const selections = tables.map(t => mapTable(t.name, t.rows)).filter(Boolean);
  return { selections, document_tables, status_map: example.status_map, notes: ['Mock Gemini (test only): mapping taken from the BetterSpace B2B example package by header match.'] };
}

function briefAnswer(prompt) {
  const keys = [...prompt.matchAll(/^- ([a-z_]+:[A-Za-z0-9_-]+) \|/gm)].map(m => m[1]);
  return { headline: 'Mock brief (test only): follow up overdue payments first.', summary: 'Generated by the local Gemini stand-in to prove the pipeline, not real analysis.', priorities: keys.slice(0, 2).map(k => ({ task_key: k, why: 'Test priority', suggested_action: 'Review this record.' })), watch_items: [], data_caveats: ['Local simulation only.'] };
}

globalThis.fetch = async (url, init = {}) => {
  const u = String(url);
  if (!u.startsWith('https://generativelanguage.googleapis.com/')) return realFetch(url, init);
  const key = init.headers?.['x-goog-api-key'];
  if (!key || u.includes('key=')) throw new Error('mock: API key must be sent in the x-goog-api-key header only');
  if (process.env.MOCK_GEMINI === '429') return new Response(JSON.stringify({ error: { code: 429, status: 'RESOURCE_EXHAUSTED', message: 'Quota exceeded (mock)' } }), { status: 429 });
  const body = JSON.parse(init.body);
  const system = body.systemInstruction.parts[0].text;
  const prompt = body.contents[0].parts[0].text;
  const answer = system.includes('Source interpretation') ? mappingAnswer(JSON.parse(prompt)) : briefAnswer(prompt);
  log.push({ kind: system.includes('Source interpretation') ? 'mapping' : 'brief', model: u.split('/models/')[1] });
  fs.writeFileSync(process.env.MOCK_GEMINI_LOG || new URL('../.state/mock-gemini.json', import.meta.url), JSON.stringify(log));
  return new Response(JSON.stringify({ candidates: [{ finishReason: 'STOP', content: { parts: [{ text: JSON.stringify(answer) }] } }], modelVersion: 'mock-gemini', usageMetadata: { promptTokenCount: prompt.length, candidatesTokenCount: 100 } }), { status: 200, headers: { 'Content-Type': 'application/json' } });
};
